name: Publish to GitHub Packages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: $registry-url(npm)
      - run: npm ci --workspaces
      - name: Build
        run: npm run build --workspaces --if-present
      - name: Publish
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
